TeamsAndPlayers/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :players

  resources :teams
  root to: "teams#index"

end

TeamsAndPlayers/app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :Team
end

TeamsAndPlayers/app/models/team.rb
class Team < ActiveRecord::Base
end

TeamsAndPlayers/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

TeamsAndPlayers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

TeamsAndPlayers/app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @players = Player.all
    respond_with(@players)
  end

  def show
    respond_with(@player)
  end

  def new
    @player = Player.new
    respond_with(@player)
  end

  def edit
  end

  def create
    @player = Player.new(player_params)
    @player.save
    respond_with(@player)
  end

  def update
    @player.update(player_params)
    respond_with(@player)
  end

  def destroy
    @player.destroy
    respond_with(@player)
  end

  private
    def set_player
      @player = Player.find(params[:id])
    end

    def player_params
      params.require(:player).permit(:playerName, :ExpertIn, :Team_id)
    end
end

TeamsAndPlayers/app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @teams = Team.all
    respond_with(@teams)
  end

  def show
    respond_with(@team)
  end

  def new
    @team = Team.new
    respond_with(@team)
  end

  def edit
  end

  def create
    @team = Team.new(team_params)
    @team.save
    respond_with(@team)
  end

  def update
    @team.update(team_params)
    respond_with(@team)
  end

  def destroy
    @team.destroy
    respond_with(@team)
  end

  private
    def set_team
      @team = Team.find(params[:id])
    end

    def team_params
      params.require(:team).permit(:TeamName, :Game)
    end
end

TeamsAndPlayers/app/helpers/application_helper.rb
module ApplicationHelper
end

TeamsAndPlayers/app/helpers/players_helper.rb
module PlayersHelper
end

TeamsAndPlayers/app/helpers/teams_helper.rb
module TeamsHelper
end

TeamsAndPlayers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeamsAndPlayers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
<header>
     <ul class="nav nav-pills pull-right">
  <% if user_signed_in? %>
    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
    <li><%= link_to "Sign up", new_user_registration_path %></li>
  <% end %>
</ul>
</header>
<%= yield %>

</body>
</html>

TeamsAndPlayers/app/views/players/_form.html.erb
<%= form_for @player, :html => { :class => "form-horizontal player" } do |f| %>

  <% if @player.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @player.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :playerName, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :playerName, :class => 'form-control' %>
    </div>
    <%=f.error_span(:playerName) %>
  </div>

  <div class="form-group">
    <%= f.label :ExpertIn, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :ExpertIn, :class => 'form-control' %>
    </div>
    <%=f.error_span(:ExpertIn) %>
  </div>

  <div class="form-group">
    <%= f.label :Team_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :Team_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:Team_id) %>
  </div>


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                players_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

TeamsAndPlayers/app/views/players/edit.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

TeamsAndPlayers/app/views/players/index.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>

      <th><%= model_class.human_attribute_name(:playerName) %></th>

      <th><%= model_class.human_attribute_name(:ExpertIn) %></th>

      <th><%= model_class.human_attribute_name(:Team_id) %></th>

      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= link_to player.id, player_path(player) %></td>

        <td><%= player.playerName %></td>

        <td><%= player.ExpertIn %></td>

        <td><%= player.Team_id %></td>

        <td><%=l player.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_player_path(player), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      player_path(player),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_player_path,
            :class => 'btn btn-primary' %>

TeamsAndPlayers/app/views/players/new.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

TeamsAndPlayers/app/views/players/show.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">

  <dt><strong><%= model_class.human_attribute_name(:playerName) %>:</strong></dt>
  <dd><%= @player.playerName %></dd>

  <dt><strong><%= model_class.human_attribute_name(:ExpertIn) %>:</strong></dt>
  <dd><%= @player.ExpertIn %></dd>

  <dt><strong><%= model_class.human_attribute_name(:Team_id) %>:</strong></dt>
  <dd><%= @player.Team_id %></dd>

</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              players_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_player_path(@player), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              player_path(@player),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>